# Task 41 – Pandas Basics
**Reference:** https://www.w3schools.com/python/pandas_tutorial.asp

In [1]:
import pandas as pd
print('Pandas version:', pd.__version__)

Pandas version: 3.0.1

In [2]:
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
df = pd.DataFrame({
    'Name':  ['Ali', 'Sara', 'Ahmed'],
    'Age':   [21, 25, 30],
    'Score': [88.5, 92.0, 78.3]
})
df

    Name  Age  Score
0    Ali   21   88.5
1   Sara   25   92.0
2  Ahmed   30   78.3

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 204.0 bytes

             Age      Score
count   3.000000   3.000000
mean   25.333333  86.266667
std     4.509250   7.117818
min    21.000000  78.300000
25%    23.000000  83.400000
50%    25.000000  88.500000
75%    27.500000  90.250000
max    30.000000  92.000000